#!/bin/bash
# build-runtime-agents.sh — concatenate a chunk's scoped context files into a
# runtime AGENTS.md that opencode v2 loads as active project instructions.
#
# Usage:  build-runtime-agents.sh <context-file-list> <target-dir> <source-label>
#   <context-file-list>  path to a file whose lines are the context files that
#                        apply to this call (the per-chunk scoped set)
#   <target-dir>         directory to write AGENTS.md into (created if absent)
#   <source-label>       human label for the generated header (e.g. "chunk 3")
# Stdout: the path of the generated AGENTS.md (or empty on failure).
#
# Why a runtime AGENTS.md instead of the old "MANDATORY: READ PROJECT CONTEXT
# FILES FIRST" block: opencode v2 loads AGENTS.md files as active instructions
# by directory scope, but does NOT load custom *_AGENTS.md, .agents/rules/*.md,
# .github/instructions/*.instructions.md, or MANDATORY_CONTEXT_FILES (only exact
# AGENTS.md is discovered natively — LADR-087). The old block listed those paths
# and told the model to read_file each one, spending tool calls against the
# chunk exploration budget. Concatenating their content into a runtime AGENTS.md
# at the chunk's cwd puts the rules in the model's system context with no
# read_file round-trip.
#
# The consumer repo's own exact AGENTS.md chain (root + nested) is NOT included
# here and must NOT be: opencode v2 discovers it natively by walking up from the
# invocation cwd to the git root, so duplicating it would inject the guidance
# twice (LADR-087). Only the custom/rule/mandatory paths — which opencode does
# not auto-load — belong in the generated file.
set -uo pipefail

_list="${1:-}"; _target_dir="${2:-}"; _label="${3:-}"

[ -n "$_target_dir" ] || { echo "build-runtime-agents.sh: missing target dir" >&2; exit 64; }
mkdir -p "$_target_dir" || { echo "build-runtime-agents.sh: cannot create $_target_dir" >&2; exit 74; }

_out="$_target_dir/AGENTS.md"

# Strip a leading YAML frontmatter block (--- ... ---) from a rule file. That
# frontmatter (applyTo:/alwaysApply:) is consumed by the scope filter to decide
# which chunk a rule applies to; it is filter metadata, not instruction content,
# and an embedded `---` block inside the runtime AGENTS.md could confuse
# opencode's own AGENTS.md parsing. Emits the tail after a leading frontmatter
# block (or the whole content when there is none / it is malformed).
_strip_frontmatter() {
  awk 'NR==1 && $0=="---" {infm=1; next}
       infm && $0=="---" {infm=0; next}
       infm {next}
       {print}' "$1"
}

cat > "$_out" <<EOF
# Runtime review instructions (${_label})

Generated by the review gate for ${_label}. These are the project rules,
standards and mandatory context that apply to this review; they override the
model's training data.

EOF

_count=0
if [ -n "$_list" ] && [ -f "$_list" ]; then
  while IFS= read -r _ctx; do
    [ -z "$_ctx" ] && continue
    # Exact standard AGENTS.md is owned by opencode v2 discovery — never
    # duplicate it (LADR-087). Custom *_AGENTS.md and rule/mandatory paths are
    # not auto-loaded, so they are appended.
    [ "$(basename "$_ctx")" = "AGENTS.md" ] && continue
    if [ ! -f "$_ctx" ]; then
      echo "  ⚠️  Runtime context file missing: $_ctx" >&2
      continue
    fi
    echo "" >> "$_out"
    echo "---" >> "$_out"
    echo "Source: \`$_ctx\`" >> "$_out"
    echo "" >> "$_out"
    _strip_frontmatter "$_ctx" >> "$_out"
    _count=$((_count + 1))
  done < "$_list"
fi

if [ "$_count" -eq 0 ]; then
  {
    echo ""
    echo "_No scoped project rule files applied to this ${_label}._"
  } >> "$_out"
fi

printf '%s\n' "$_out"
